version: "3.7"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcc-portal
    image: mxavier27/tcc-eletrica-portal:latest
    ports:
      - "8080:8080"